package com.bookstore.entities;

public enum BookCategory {

	ACTION_AND_ADVENTURE, AUTOBIOGRAPHY, 
	BIOGRAPHY, 
	CHILDREN, CLASSICS, COMICS, COOK_BOOKS, CRAFTS_AND_HOBBIES,  
	DRAMA, 
	ENCYCLOPEDIA, 
	FANTASY, FICTION, 
	HEALTH, HISTORICAL_FICTION, HISTORY, HORROR, HUMOUR, 
	MYSTERY, MYTHOLOGY, 
	POETRY, 
	ROMANCE, 
	SCIENCE_FICTION, SELF_HELP, SHORT_STORIES, SPIRITUALITY, SUSPENSE_AND_THRILLER
	
	
}
